// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CamControlMZ","status":false,"description":"(v.1.7) Allows greater control over where the game camera is focused. View documentation for plugin commands.","parameters":{"useZoom":"true","bZoom":"1"}},
{"name":"GALV_MapTravelMZ","status":false,"description":"(v.1.1) A new scene allowing you to fast travel by selecting locations on a map","parameters":{"varMap":"1","xVar":"2","yVar":"3","textConfirm":"Travel","textCancel":"Cancel","windowWidth":"180","spriteFrames":"3","frameSpeed":"10"}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"ButtonPicture","status":false,"description":"Makes a picture clickable.","parameters":{}},
{"name":"GALV_MessageBackgroundMZ","status":false,"description":"(v.1.0) Displays an image behind messages in place of the windowskin","parameters":{"defaultStatus":"true"}},
{"name":"GALV_MessageBustsMZ","status":false,"description":"(v.1.2) Displays a bust image instead of selected face image","parameters":{"bPriority":"0","bPosition":"0","bX":"0","bY":"0","xOffset":"390","fileAppend":"","mStyleBusts":"false"}},
{"name":"GALV_MessageStylesMZ","status":false,"description":"(v.2.1) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"false","aGraphic":"WindowArrow","yOffset":"60"}},
{"name":"GALV_MessageTimerMZ","status":false,"description":"(v.1.2) Visual timer for messages and choices.","parameters":{"globalTimer":"0","timerHeight":"10","timerMaxWidth":"","timerPadding":"10","timerPos":"top","timerOffset":"0,0","timerColor1":"0,0,0,0.5","timerColor2":"255,255,255,1"}}
];
